
version: '3'
services:
    mysqldb:
        image: mysql
        networks:
            - hotel-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: lozinka
            MYSQL_DATABASE: hotel-service 
        ports:
            - 3308:3306
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 45s
            interval: 10s
            retries: 10
    hotel-service:
        build:
            context: .
            dockerfile: Dockerfile
        image: hotel-service
        ports:
            - 8200:8200
        networks:
            - hotel-mysql
        depends_on:
            mysqldb:
                  condition: service_healthy
networks:
  hotel-mysql:            
       
   